language: node_js
sudo: required
node_js:
  - 7.9.0

cache:
  directories:
    - node_modules

jobs:
  include:
    - stage: pre cache
      script:
        - npm install -g hexo-cli
        - npm install
        - npm install hexo-deployer-git --save
    - stage: generate_html
      script: hexo clean
    - stage: generate_html
      script: hexo generate
    - stage: deploy
      script: sed -i "s/gh_token/${GH_TOKEN}/g" ./_config.yml
    - stage: deploy
      script: cat ./_config.yml
    - stage: deploy to GitHub pages
      script: hexo deploy

#after_script:
#  - git config user.name "Phil Huang"
#  - git config user.email "phil.huang@redhat.com"
#  - sed -i "s/gh_token/${GH_TOKEN}/g" ./_config.yml
#  - cat ./_config.yml
#  - hexo deploy
# E: Build LifeCycle
