language: node_js
sudo: required
node_js:
  - 7.9.0

cache:
  directories:
    - node_modules

before_install:
  - npm install -g hexo-cli

# S: Build Lifecycle
install:
  - npm install
  - npm install hexo-deployer-git --save

script:
  - hexo clean
  - hexo generate

after_script:
  - git config user.name "Phil Huang"
  - git config user.email "phil.huang@redhat.com"
  - sed -i "s/gh_token/${GH_TOKEN}/g" ./_config.yml
  - cat ./_config.yml
  - hexo deploy
# E: Build LifeCycle
