# Header
menu:
  Home: /
  Archives: /archives
#  CV: /CV
rss: /atom.xml

# Content
excerpt_link: Poke Me
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- recent_posts
#- archive

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics: UA-90856047-1
favicon: /favicon.ico
twitter: pichuang_tw
google_plus:
fb_admins:
fb_app_id:
speakerdeck: pichuang
facebook: paulintoro
linkedin: phil-huang-09b09895
github: pichuang

